### ISSUE TITLE
webpack 中 loader 和 plugin 的区别是什么

### ISSUE THREAD

**Issue by CatsAndMice** [CatsAndMice/Blog#12]

**Comment by lihai-boop** [comment]
loader是一个文件加载器，能够加载资源文件，并对这些文件进行处理，例如编译，压缩等,最终打包到一个指定的文件中；
1. 处理一个文件可以使用多个loader，loader执行顺序是相反的，最后一个loader先执行，第一个loader最后执行
2. 第一个执行的loader接收源文件的内容作为参数，其它loader接收前一个执行loader的返回值作为参数，最后执行的loader会返回此模块的js代码

plugin:是webpack功能扩展的工具，webpack执行过程中会广播出许多事件，plugin可以监听这些事件，在合适的时机通过webpack提供的API改变输出结果。


两者区别:
1. loader，它是一个转换器，将a文件转换成b文件，比如a.scss转换成a.css，单纯的文件转换过程
2. plugin是一个扩展器，它丰富了webpack，针对loader结束后，webpack打包整个过程，它并不操作文件，而是基于事件机制工作，会监听webpack打包过程的某些节点，执行广泛的任务
