### ISSUE TITLE
什么是防抖和节流，他们的应用场景有哪些 

### ISSUE THREAD

**Issue by CatsAndMice** [CatsAndMice/Blog#14]

**Comment by lihai-boop** [comment]
### 防抖
n秒后执行，如果n秒内再次触发，则重新计算时间
### 节流
n秒内只执行一次

节流与防抖实现代码，已在个人封装<a href="https://github.com/lihai-boop/tool/blob/master/src/debounceAndThrottle/DebounceAndThrottle.js">@lihai-js/tool</a> 实现

应用场景：
防抖：
* 搜索框监听输入事件请求加载
* 浏览器窗口`resize`事件
* 监听鼠标滚动事件`onscroll`

节流:
* 表单提交按钮点击事件
