### ISSUE TITLE
v-if、v-show、v-html 的原理是什么，它是如何封装的？

### ISSUE THREAD

**Issue by CatsAndMice** [CatsAndMice/Blog#15]
如何根据v-if的原理写一个v-permission,要求切换权限时节点可以被删除,也可以在删除后被添加回来

https://stackoverflow.com/questions/43003976/a-custom-directive-similar-to-v-if-in-vuejs

**Comment by lihai-boop** [comment]
v-show:通过控制属性`display`来控制元素是否展示,保留结构
v-html是通过`innterHTML`修改内容
v-if:隐藏结构并直接从整个dom树中移除
