### ISSUE TITLE
浏览器缓存 ETag 里的值是怎么生成的

### ISSUE THREAD

**Issue by CatsAndMice** [CatsAndMice/Blog#8]

**Comment by lihai-boop** [comment]
**ETag**是http的一部分，它是若干缓存中的进行 **缓存协商** 的一种机制。  

`ETag`是一个不透明的标识符，它由web服务器根据url上资源的版本而定，当url上的资源更新变化后，ETag也会随之改变。**ETag用于快速比较判断出url资源是否发生变化**。  
ETag语法：
```
ETag:W/"<etag_value>"

ETag:"<etag_value>"
```
`W/(可选)`: 'W/'(大小写敏感)，表示使用弱验证器。易生成ETag，但不利于比较，相同的资源可能弱ETag相同，但它们每一个字母并不都相同
“<etag_value>”:利用j时间戳等生成的ETag唯一

ETag的使用:
url请求时，服务器会返回资源与对应的ETag值

<img src="https://p.pstatp.com/origin/pgc-image/6f40c062e7074242bd46ab01bc98c12d" />

客户端决定是否缓存这个资源和ETag。以后客户端想再次请求相同的url,将会发送一个保存`Etag`和`If-None-Match`字段请求。

<img src="https://p.pstatp.com/origin/pgc-image/8705c6bfbb8348069a32a1a21c78cffc" />
收到客户端请求后，服务端会比较客户端ETag和当前资源的Etag。如果ETag匹配，则服务端发送一个极短的响应，包含http"304未修改"的状态，304状态告诉客户端，该资源版本是最新的，可以使用它。
<img src="https://p.pstatp.com/origin/pgc-image/9f8f9ced73634cb295977242aca06543" />


<a href="https://jishuin.proginn.com/p/763bfbd5b14e">https://jishuin.proginn.com/p/763bfbd5b14e</a>
