### ISSUE TITLE
弹性盒子中 flex: 0 1 auto 表示什么意思

### ISSUE THREAD

**Issue by CatsAndMice** [CatsAndMice/Blog#9]

**Comment by lihai-boop** [comment]
`flex：0 1 auto；`是一个复合缩写属性
它分别表示:
`flex-grow`:指定flex容器剩余空间可以分配到的比例
`flex-shrink`:指定元素收缩规则，宽度大于容器宽度时才会发生收缩
`flex-basis`:指定`flex`元素的初始宽度
